############# Lietuviška navigacija ##############

# pagrindinis meniu
[[main]]
name = "Pradžia"
url = ""
weight = 1

[[main]]
name = "Apie"
url = "about"
weight = 2


[[main]]
name = "Projektai"
url = "projects"
weight = 4

[[main]]
parent = "Puslapiai"
name = "Kontaktai"
url = "contact"

[[main]]
parent = "Puslapiai"
name = "Kategorijos"
url = "categories"


# poraštės meniu
[[footer]]
name = "Apie"
url = "about"
weight = 1

[[footer]]
name = "Kontaktai"
url = "contact"
weight = 2

[[footer]]
name = "Privatumo Politika"
url = "privacy-policy"
weight = 3
