services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8333:80"
    networks:
      - nordics-software
networks:
  nordics-software:
    name: any-internal-network



